import { pgTable, uuid, text, integer, numeric, boolean, jsonb, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

export const crmPipelines = pgTable('crm_pipelines', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  description: text('description'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  isDefault: boolean('is_default').default(false),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const crmPipelineStages = pgTable('crm_pipeline_stages', {
  id: uuid('id').primaryKey().defaultRandom(),
  pipelineId: uuid('pipeline_id').notNull(),
  name: text('name').notNull(),
  color: text('color').default('#6b7280'),
  probability: integer('probability').default(0),
  orderIndex: integer('order_index').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const crmTags = pgTable('crm_tags', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  color: text('color').default('#6b7280'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
}, t => ({ uniqueName: uniqueIndex().on(t.organizationId, t.name) }))

export const crmCompanies = pgTable('crm_companies', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  industry: text('industry'),
  employeeCount: integer('employee_count'),
  revenue: numeric('revenue', { precision: 15, scale: 2 }),
  addressLine1: text('address_line1'),
  addressLine2: text('address_line2'),
  city: text('city'),
  state: text('state'),
  zip: text('zip'),
  country: text('country'),
  website: text('website'),
  phone: text('phone'),
  email: text('email'),
  gstNumber: text('gst_number'),
  logoUrl: text('logo_url'),
  description: text('description'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  assignedTo: uuid('assigned_to'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const crmLeads = pgTable('crm_leads', {
  id: uuid('id').primaryKey().defaultRandom(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email'),
  phone: text('phone'),
  jobTitle: text('job_title'),
  companyId: uuid('company_id'),
  companyName: text('company_name'),
  website: text('website'),
  industry: text('industry'),
  leadSource: text('lead_source'),
  priority: text('priority'),
  status: text('status').notNull().default('new'),
  pipelineStageId: uuid('pipeline_stage_id'),
  estimatedDealValue: numeric('estimated_deal_value', { precision: 15, scale: 2 }),
  expectedCloseDate: timestamp('expected_close_date', { mode: 'date' }),
  description: text('description'),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  assignedTo: uuid('assigned_to'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const crmContacts = pgTable('crm_contacts', {
  id: uuid('id').primaryKey().defaultRandom(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email'),
  phone: text('phone'),
  jobTitle: text('job_title'),
  department: text('department'),
  companyId: uuid('company_id'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  assignedTo: uuid('assigned_to'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const crmDeals = pgTable('crm_deals', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  dealValue: numeric('deal_value', { precision: 15, scale: 2 }).default('0'),
  probability: integer('probability').default(0),
  pipelineId: uuid('pipeline_id').notNull(),
  pipelineStageId: uuid('pipeline_stage_id').notNull(),
  leadId: uuid('lead_id'),
  companyId: uuid('company_id'),
  contactId: uuid('contact_id'),
  expectedCloseDate: timestamp('expected_close_date', { mode: 'date' }),
  actualCloseDate: timestamp('actual_close_date', { mode: 'date' }),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  assignedTo: uuid('assigned_to'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const crmActivities = pgTable('crm_activities', {
  id: uuid('id').primaryKey().defaultRandom(),
  type: text('type').notNull(),
  subject: text('subject').notNull(),
  description: text('description'),
  activityDate: timestamp('activity_date').defaultNow(),
  durationMinutes: integer('duration_minutes'),
  leadId: uuid('lead_id'),
  companyId: uuid('company_id'),
  contactId: uuid('contact_id'),
  dealId: uuid('deal_id'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  assignedTo: uuid('assigned_to'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const crmNotes = pgTable('crm_notes', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title'),
  content: text('content'),
  isPinned: boolean('is_pinned').default(false),
  isPrivate: boolean('is_private').default(false),
  leadId: uuid('lead_id'),
  companyId: uuid('company_id'),
  contactId: uuid('contact_id'),
  dealId: uuid('deal_id'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const crmTasks = pgTable('crm_tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  description: text('description'),
  status: text('status').notNull().default('pending'),
  priority: text('priority').notNull().default('medium'),
  dueDate: timestamp('due_date'),
  reminderAt: timestamp('reminder_at'),
  isRecurring: boolean('is_recurring').default(false),
  recurringInterval: text('recurring_interval'),
  leadId: uuid('lead_id'),
  companyId: uuid('company_id'),
  contactId: uuid('contact_id'),
  dealId: uuid('deal_id'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  assignedTo: uuid('assigned_to'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  completedAt: timestamp('completed_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const crmTimeline = pgTable('crm_timeline', {
  id: uuid('id').primaryKey().defaultRandom(),
  action: text('action').notNull(),
  description: text('description'),
  entityType: text('entity_type').notNull(),
  entityId: uuid('entity_id').notNull(),
  leadId: uuid('lead_id'),
  companyId: uuid('company_id'),
  contactId: uuid('contact_id'),
  dealId: uuid('deal_id'),
  metadata: jsonb('metadata').default('{}'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const crmEntityTags = pgTable('crm_entity_tags', {
  id: uuid('id').primaryKey().defaultRandom(),
  tagId: uuid('tag_id').notNull(),
  entityType: text('entity_type').notNull(),
  entityId: uuid('entity_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
}, t => ({ unique: uniqueIndex().on(t.tagId, t.entityType, t.entityId) }))
