import {
  pgTable,
  uuid,
  text,
  integer,
  numeric,
  boolean,
  jsonb,
  timestamp,
  date,
} from 'drizzle-orm/pg-core'

export const documentFolders = pgTable('document_folders', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  description: text('description'),
  parentId: uuid('parent_id'),
  color: text('color').default('#3b82f6'),
  icon: text('icon'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const documents = pgTable('documents', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  description: text('description'),
  documentType: text('document_type').notNull().default('document'),
  content: jsonb('content'),
  contentText: text('content_text'),
  mimeType: text('mime_type').default('text/plain'),
  fileUrl: text('file_url'),
  fileSize: integer('file_size').default(0),
  folderId: uuid('folder_id'),
  ownerId: uuid('owner_id'),
  departmentId: uuid('department_id'),
  status: text('status').notNull().default('draft'),
  currentVersion: integer('current_version').default(1),
  isArchived: boolean('is_archived').default(false),
  expirationDate: timestamp('expiration_date'),
  effectiveDate: timestamp('effective_date'),
  templateId: uuid('template_id'),
  tags: text('tags').array().default([]),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const documentVersions = pgTable('document_versions', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  versionNumber: integer('version_number').notNull(),
  content: jsonb('content'),
  contentText: text('content_text'),
  changeSummary: text('change_summary'),
  createdBy: uuid('created_by').notNull(),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const documentShares = pgTable('document_shares', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  shareType: text('share_type').notNull().default('user'),
  sharedWithUserId: uuid('shared_with_user_id'),
  sharedWithTeamId: uuid('shared_with_team_id'),
  sharedWithDepartmentId: uuid('shared_with_department_id'),
  permission: text('permission').notNull().default('view'),
  shareToken: text('share_token'),
  expiresAt: timestamp('expires_at'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const documentComments = pgTable('document_comments', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  parentId: uuid('parent_id'),
  content: text('content').notNull(),
  mentions: jsonb('mentions').default('[]'),
  isResolved: boolean('is_resolved').default(false),
  resolvedBy: uuid('resolved_by'),
  resolvedAt: timestamp('resolved_at'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const documentApprovals = pgTable('document_approvals', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  requestedBy: uuid('requested_by').notNull(),
  assignedTo: uuid('assigned_to'),
  status: text('status').notNull().default('pending'),
  comment: text('comment'),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  respondedAt: timestamp('responded_at'),
})

export const documentApprovalHistory = pgTable('document_approval_history', {
  id: uuid('id').primaryKey().defaultRandom(),
  approvalId: uuid('approval_id').notNull(),
  action: text('action').notNull(),
  comment: text('comment'),
  performedBy: uuid('performed_by').notNull(),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const documentTemplates = pgTable('document_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  description: text('description'),
  documentType: text('document_type').notNull().default('document'),
  content: jsonb('content'),
  contentText: text('content_text'),
  category: text('category'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  isSystem: boolean('is_system').default(false),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const knowledgeArticles = pgTable('knowledge_articles', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  summary: text('summary'),
  content: jsonb('content'),
  contentText: text('content_text'),
  category: text('category').notNull().default('General'),
  tags: text('tags').array().default([]),
  status: text('status').notNull().default('draft'),
  authorId: uuid('author_id'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const documentSops = pgTable('document_sops', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  purpose: text('purpose'),
  scope: text('scope'),
  departmentId: uuid('department_id'),
  ownerId: uuid('owner_id'),
  steps: jsonb('steps').default('[]'),
  requiredInputs: jsonb('required_inputs').default('[]'),
  expectedOutputs: jsonb('expected_outputs').default('[]'),
  relatedDocumentIds: text('related_document_ids').array().default([]),
  version: integer('version').default(1),
  approvalStatus: text('approval_status').notNull().default('draft'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const documentPolicies = pgTable('document_policies', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  policyType: text('policy_type').notNull().default('company'),
  summary: text('summary'),
  content: jsonb('content'),
  contentText: text('content_text'),
  departmentId: uuid('department_id'),
  ownerId: uuid('owner_id'),
  version: integer('version').default(1),
  effectiveDate: date('effective_date'),
  expirationDate: date('expiration_date'),
  approvalStatus: text('approval_status').notNull().default('draft'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const documentContracts = pgTable('document_contracts', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  contractNumber: text('contract_number'),
  customerId: uuid('customer_id'),
  companyId: uuid('company_id'),
  dealId: uuid('deal_id'),
  projectId: uuid('project_id'),
  startDate: date('start_date'),
  endDate: date('end_date'),
  renewalDate: date('renewal_date'),
  value: numeric('value', { precision: 15, scale: 2 }),
  currency: text('currency').default('USD'),
  status: text('status').notNull().default('draft'),
  ownerId: uuid('owner_id'),
  documentId: uuid('document_id'),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const documentRelationships = pgTable('document_relationships', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  entityType: text('entity_type').notNull(),
  entityId: uuid('entity_id').notNull(),
  metadata: jsonb('metadata').default('{}'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const documentActivities = pgTable('document_activities', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  userId: uuid('user_id').notNull(),
  action: text('action').notNull(),
  resource: text('resource').notNull(),
  resourceId: uuid('resource_id'),
  documentId: uuid('document_id'),
  metadata: jsonb('metadata').default('{}'),
  createdAt: timestamp('created_at').defaultNow(),
})