import { pgTable, uuid, text, integer, numeric, boolean, jsonb, timestamp, uniqueIndex, date } from 'drizzle-orm/pg-core'

export const financeProductCategories = pgTable('finance_product_categories', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  description: text('description'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financeProducts = pgTable('finance_products', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  sku: text('sku'),
  categoryId: uuid('category_id'),
  description: text('description'),
  unitPrice: numeric('unit_price', { precision: 15, scale: 2 }).notNull().default('0'),
  unit: text('unit').default('piece'),
  taxRateId: uuid('tax_rate_id'),
  type: text('type').notNull().default('product'),
  status: text('status').notNull().default('active'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financeTaxRates = pgTable('finance_tax_rates', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  rate: numeric('rate', { precision: 5, scale: 2 }).notNull(),
  type: text('type').notNull().default('sales_tax'),
  isDefault: boolean('is_default').default(false),
  isCompound: boolean('is_compound').default(false),
  appliesTo: text('applies_to').array().default([]),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financeQuotations = pgTable('finance_quotations', {
  id: uuid('id').primaryKey().defaultRandom(),
  quoteNumber: text('quote_number').notNull(),
  clientName: text('client_name').notNull(),
  clientEmail: text('client_email'),
  clientPhone: text('client_phone'),
  companyId: uuid('company_id'),
  dealId: uuid('deal_id'),
  projectId: uuid('project_id'),
  issueDate: timestamp('issue_date', { mode: 'date' }).notNull(),
  expiryDate: timestamp('expiry_date', { mode: 'date' }),
  currency: text('currency').notNull().default('USD'),
  subtotal: numeric('subtotal', { precision: 15, scale: 2 }).notNull().default('0'),
  discountType: text('discount_type'),
  discountValue: numeric('discount_value', { precision: 15, scale: 2 }).default('0'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).default('0'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).default('0'),
  total: numeric('total', { precision: 15, scale: 2 }).notNull().default('0'),
  notes: text('notes'),
  terms: text('terms'),
  status: text('status').notNull().default('draft'),
  type: text('type').notNull().default('quote'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financeQuotationItems = pgTable('finance_quotation_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  quotationId: uuid('quotation_id').notNull(),
  productId: uuid('product_id'),
  description: text('description').notNull(),
  quantity: numeric('quantity', { precision: 10, scale: 2 }).notNull().default('1'),
  unitPrice: numeric('unit_price', { precision: 15, scale: 2 }).notNull().default('0'),
  discountPercent: numeric('discount_percent', { precision: 5, scale: 2 }).default('0'),
  taxRateId: uuid('tax_rate_id'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).default('0'),
  total: numeric('total', { precision: 15, scale: 2 }).notNull().default('0'),
  sortOrder: integer('sort_order').default(0),
  createdAt: timestamp('created_at').defaultNow(),
})

export const financeInvoices = pgTable('finance_invoices', {
  id: uuid('id').primaryKey().defaultRandom(),
  invoiceNumber: text('invoice_number').notNull(),
  clientName: text('client_name').notNull(),
  clientEmail: text('client_email'),
  clientPhone: text('client_phone'),
  companyId: uuid('company_id'),
  dealId: uuid('deal_id'),
  projectId: uuid('project_id'),
  quotationId: uuid('quotation_id'),
  issueDate: timestamp('issue_date', { mode: 'date' }).notNull(),
  dueDate: timestamp('due_date', { mode: 'date' }).notNull(),
  currency: text('currency').notNull().default('USD'),
  subtotal: numeric('subtotal', { precision: 15, scale: 2 }).notNull().default('0'),
  discountType: text('discount_type'),
  discountValue: numeric('discount_value', { precision: 15, scale: 2 }).default('0'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).default('0'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).default('0'),
  total: numeric('total', { precision: 15, scale: 2 }).notNull().default('0'),
  amountPaid: numeric('amount_paid', { precision: 15, scale: 2 }).default('0'),
  balanceDue: numeric('balance_due', { precision: 15, scale: 2 }).default('0'),
  notes: text('notes'),
  terms: text('terms'),
  status: text('status').notNull().default('draft'),
  isRecurring: boolean('is_recurring').default(false),
  recurringFrequency: text('recurring_frequency'),
  recurringNextDate: timestamp('recurring_next_date', { mode: 'date' }),
  recurringEndDate: timestamp('recurring_end_date', { mode: 'date' }),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financeInvoiceItems = pgTable('finance_invoice_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  invoiceId: uuid('invoice_id').notNull(),
  productId: uuid('product_id'),
  description: text('description').notNull(),
  quantity: numeric('quantity', { precision: 10, scale: 2 }).notNull().default('1'),
  unitPrice: numeric('unit_price', { precision: 15, scale: 2 }).notNull().default('0'),
  discountPercent: numeric('discount_percent', { precision: 5, scale: 2 }).default('0'),
  taxRateId: uuid('tax_rate_id'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).default('0'),
  total: numeric('total', { precision: 15, scale: 2 }).notNull().default('0'),
  sortOrder: integer('sort_order').default(0),
  createdAt: timestamp('created_at').defaultNow(),
})

export const financePaymentMethods = pgTable('finance_payment_methods', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  code: text('code').notNull().unique(),
  description: text('description'),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
})

export const financePayments = pgTable('finance_payments', {
  id: uuid('id').primaryKey().defaultRandom(),
  invoiceId: uuid('invoice_id'),
  amount: numeric('amount', { precision: 15, scale: 2 }).notNull(),
  currency: text('currency').notNull().default('USD'),
  paymentMethodId: uuid('payment_method_id'),
  paymentMethodName: text('payment_method_name'),
  transactionReference: text('transaction_reference'),
  status: text('status').notNull().default('completed'),
  paymentDate: timestamp('payment_date').notNull().defaultNow(),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financeExpenseCategories = pgTable('finance_expense_categories', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  description: text('description'),
  color: text('color').default('#6b7280'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financeExpenses = pgTable('finance_expenses', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  categoryId: uuid('category_id'),
  vendor: text('vendor'),
  projectId: uuid('project_id'),
  companyId: uuid('company_id'),
  amount: numeric('amount', { precision: 15, scale: 2 }).notNull(),
  currency: text('currency').notNull().default('USD'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).default('0'),
  expenseDate: timestamp('expense_date', { mode: 'date' }).notNull(),
  receiptUrl: text('receipt_url'),
  notes: text('notes'),
  billable: boolean('billable').default(false),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financePurchaseOrders = pgTable('finance_purchase_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  poNumber: text('po_number').notNull(),
  vendorName: text('vendor_name').notNull(),
  vendorEmail: text('vendor_email'),
  vendorPhone: text('vendor_phone'),
  projectId: uuid('project_id'),
  issueDate: timestamp('issue_date', { mode: 'date' }).notNull(),
  deliveryDate: timestamp('delivery_date', { mode: 'date' }),
  currency: text('currency').notNull().default('USD'),
  subtotal: numeric('subtotal', { precision: 15, scale: 2 }).notNull().default('0'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).default('0'),
  total: numeric('total', { precision: 15, scale: 2 }).notNull().default('0'),
  notes: text('notes'),
  terms: text('terms'),
  status: text('status').notNull().default('draft'),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const financePurchaseOrderItems = pgTable('finance_purchase_order_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  purchaseOrderId: uuid('purchase_order_id').notNull(),
  productId: uuid('product_id'),
  description: text('description').notNull(),
  quantity: numeric('quantity', { precision: 10, scale: 2 }).notNull().default('1'),
  unitPrice: numeric('unit_price', { precision: 15, scale: 2 }).notNull().default('0'),
  taxRateId: uuid('tax_rate_id'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).default('0'),
  total: numeric('total', { precision: 15, scale: 2 }).notNull().default('0'),
  sortOrder: integer('sort_order').default(0),
  createdAt: timestamp('created_at').defaultNow(),
})
