import { pgTable, uuid, text, integer, numeric, boolean, jsonb, timestamp, time, date, uniqueIndex } from 'drizzle-orm/pg-core'

export const hrDepartments = pgTable('hr_departments', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  description: text('description'),
  managerId: uuid('manager_id'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
}, t => ({ uniqueOrgSlug: uniqueIndex().on(t.organizationId, t.slug) }))

export const hrWorkSchedules = pgTable('hr_work_schedules', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  description: text('description'),
  workingDays: text('working_days').array().default(['mon', 'tue', 'wed', 'thu', 'fri']),
  startTime: time('start_time'),
  endTime: time('end_time'),
  weeklyHours: numeric('weekly_hours', { precision: 5, scale: 2 }).default('40'),
  shift: text('shift').default('day'),
  flexible: boolean('flexible').default(false),
  workMode: text('work_mode').default('office'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrEmployees = pgTable('hr_employees', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeCode: text('employee_code'),
  userId: uuid('user_id'),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email'),
  phone: text('phone'),
  profilePhoto: text('profile_photo'),
  dateOfBirth: date('date_of_birth'),
  gender: text('gender'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  postalCode: text('postal_code'),
  country: text('country'),
  departmentId: uuid('department_id'),
  teamId: uuid('team_id'),
  jobTitle: text('job_title'),
  managerId: uuid('manager_id'),
  employmentType: text('employment_type').notNull().default('full_time'),
  employmentStatus: text('employment_status').notNull().default('active'),
  joiningDate: date('joining_date'),
  exitDate: date('exit_date'),
  location: text('location'),
  workScheduleId: uuid('work_schedule_id'),
  workMode: text('work_mode').default('office'),
  emergencyContact: jsonb('emergency_contact').default('{}'),
  skills: jsonb('skills').default('[]'),
  settings: jsonb('settings').default('{}'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
}, t => ({ uniqueOrgCode: uniqueIndex().on(t.organizationId, t.employeeCode) }))

export const hrEmployeeSkills = pgTable('hr_employee_skills', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  skill: text('skill').notNull(),
  level: text('level').notNull().default('beginner'),
  yearsExperience: numeric('years_experience', { precision: 5, scale: 2 }).default('0'),
  certification: text('certification'),
  verified: boolean('verified').default(false),
  verifiedBy: uuid('verified_by'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, t => ({ unique: uniqueIndex().on(t.employeeId, t.skill) }))

export const hrAttendance = pgTable('hr_attendance', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  attendanceDate: date('attendance_date').notNull(),
  checkIn: timestamp('check_in'),
  checkOut: timestamp('check_out'),
  status: text('status').notNull().default('present'),
  workingMinutes: integer('working_minutes').default(0),
  overtimeMinutes: integer('overtime_minutes').default(0),
  lateMinutes: integer('late_minutes').default(0),
  earlyDepartureMinutes: integer('early_departure_minutes').default(0),
  notes: text('notes'),
  createdBy: uuid('created_by').notNull(),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, t => ({ unique: uniqueIndex().on(t.employeeId, t.attendanceDate) }))

export const hrHolidays = pgTable('hr_holidays', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  holidayDate: date('holiday_date').notNull(),
  holidayType: text('holiday_type').notNull().default('public'),
  departmentId: uuid('department_id'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
}, t => ({ unique: uniqueIndex().on(t.organizationId, t.name, t.holidayDate) }))

export const hrLeaveTypes = pgTable('hr_leave_types', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  code: text('code').notNull(),
  color: text('color').default('#3b82f6'),
  daysPerYear: numeric('days_per_year', { precision: 5, scale: 1 }).default('0'),
  carryOver: numeric('carry_over', { precision: 5, scale: 1 }).default('0'),
  requiresApproval: boolean('requires_approval').default(true),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
}, t => ({ uniqueOrgCode: uniqueIndex().on(t.organizationId, t.code) }))

export const hrLeaveBalances = pgTable('hr_leave_balances', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  leaveTypeId: uuid('leave_type_id').notNull(),
  year: integer('year').notNull(),
  totalDays: numeric('total_days', { precision: 5, scale: 1 }).default('0'),
  usedDays: numeric('used_days', { precision: 5, scale: 1 }).default('0'),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, t => ({ unique: uniqueIndex().on(t.employeeId, t.leaveTypeId, t.year) }))

export const hrLeaveRequests = pgTable('hr_leave_requests', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  leaveTypeId: uuid('leave_type_id').notNull(),
  startDate: date('start_date').notNull(),
  endDate: date('end_date').notNull(),
  days: numeric('days', { precision: 5, scale: 1 }).notNull().default('1'),
  reason: text('reason'),
  status: text('status').notNull().default('pending'),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),
  reviewedAt: timestamp('reviewed_at'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrJobOpenings = pgTable('hr_job_openings', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  departmentId: uuid('department_id'),
  teamId: uuid('team_id'),
  hiringManagerId: uuid('hiring_manager_id'),
  location: text('location'),
  employmentType: text('employment_type').default('full_time'),
  salaryMin: numeric('salary_min', { precision: 15, scale: 2 }),
  salaryMax: numeric('salary_max', { precision: 15, scale: 2 }),
  currency: text('currency').default('USD'),
  requiredSkills: text('required_skills').array().default([]),
  description: text('description'),
  status: text('status').notNull().default('draft'),
  workspaceId: uuid('workspace_id'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrCandidates = pgTable('hr_candidates', {
  id: uuid('id').primaryKey().defaultRandom(),
  jobOpeningId: uuid('job_opening_id'),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email'),
  phone: text('phone'),
  resumeUrl: text('resume_url'),
  skills: text('skills').array().default([]),
  experienceYears: numeric('experience_years', { precision: 5, scale: 2 }).default('0'),
  source: text('source'),
  stage: text('stage').notNull().default('applied'),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrInterviews = pgTable('hr_interviews', {
  id: uuid('id').primaryKey().defaultRandom(),
  candidateId: uuid('candidate_id').notNull(),
  jobOpeningId: uuid('job_opening_id'),
  interviewerIds: uuid('interviewer_ids').array().default([]),
  interviewType: text('interview_type').default('video'),
  scheduledAt: timestamp('scheduled_at'),
  durationMinutes: integer('duration_minutes').default(60),
  location: text('location'),
  meetingUrl: text('meeting_url'),
  notes: text('notes'),
  feedback: text('feedback'),
  score: integer('score'),
  status: text('status').notNull().default('scheduled'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrOffers = pgTable('hr_offers', {
  id: uuid('id').primaryKey().defaultRandom(),
  candidateId: uuid('candidate_id').notNull(),
  jobOpeningId: uuid('job_opening_id'),
  position: text('position').notNull(),
  salary: numeric('salary', { precision: 15, scale: 2 }),
  currency: text('currency').default('USD'),
  joiningDate: date('joining_date'),
  benefits: jsonb('benefits').default('{}'),
  notes: text('notes'),
  expiryDate: date('expiry_date'),
  status: text('status').notNull().default('draft'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrOnboardingTemplates = pgTable('hr_onboarding_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  description: text('description'),
  steps: jsonb('steps').default('[]'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrOnboardingAssignments = pgTable('hr_onboarding_assignments', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  templateId: uuid('template_id'),
  status: text('status').notNull().default('not_started'),
  startedAt: timestamp('started_at'),
  completedAt: timestamp('completed_at'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrOnboardingTasks = pgTable('hr_onboarding_tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  assignmentId: uuid('assignment_id').notNull(),
  title: text('title').notNull(),
  description: text('description'),
  assignedTo: uuid('assigned_to'),
  dueDate: date('due_date'),
  status: text('status').notNull().default('pending'),
  completedAt: timestamp('completed_at'),
  sortOrder: integer('sort_order').default(0),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrOffboardingRequests = pgTable('hr_offboarding_requests', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  exitDate: date('exit_date'),
  reason: text('reason'),
  noticePeriodDays: integer('notice_period_days').default(0),
  status: text('status').notNull().default('requested'),
  managerReview: text('manager_review'),
  assetReturned: boolean('asset_returned').default(false),
  accessRevoked: boolean('access_revoked').default(false),
  finalDocuments: boolean('final_documents').default(false),
  exitInterviewNotes: text('exit_interview_notes'),
  approvedBy: uuid('approved_by'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrPerformanceCycles = pgTable('hr_performance_cycles', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  periodType: text('period_type').notNull().default('quarterly'),
  startDate: date('start_date'),
  endDate: date('end_date'),
  status: text('status').notNull().default('planned'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrPerformanceReviews = pgTable('hr_performance_reviews', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  cycleId: uuid('cycle_id').notNull(),
  reviewerId: uuid('reviewer_id'),
  rating: numeric('rating', { precision: 3, scale: 2 }),
  goalsAchieved: text('goals_achieved'),
  strengths: text('strengths'),
  improvements: text('improvements'),
  overallFeedback: text('overall_feedback'),
  developmentPlan: text('development_plan'),
  status: text('status').notNull().default('draft'),
  submittedAt: timestamp('submitted_at'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
}, t => ({ unique: uniqueIndex().on(t.employeeId, t.cycleId) }))

export const hrGoals = pgTable('hr_goals', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  description: text('description'),
  goalLevel: text('goal_level').notNull().default('employee'),
  parentGoalId: uuid('parent_goal_id'),
  departmentId: uuid('department_id'),
  employeeId: uuid('employee_id'),
  ownerId: uuid('owner_id'),
  target: numeric('target', { precision: 10, scale: 2 }),
  currentValue: numeric('current_value', { precision: 10, scale: 2 }).default('0'),
  progress: integer('progress').default(0),
  deadline: date('deadline'),
  status: text('status').notNull().default('not_started'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrCompensation = pgTable('hr_compensation', {
  id: uuid('id').primaryKey().defaultRandom(),
  employeeId: uuid('employee_id').notNull(),
  baseSalary: numeric('base_salary', { precision: 15, scale: 2 }),
  currency: text('currency').default('USD'),
  payCycle: text('pay_cycle').default('monthly'),
  effectiveDate: date('effective_date'),
  updatedBy: uuid('updated_by'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const hrActivities = pgTable('hr_activities', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  userId: uuid('user_id').notNull(),
  action: text('action').notNull(),
  resource: text('resource').notNull(),
  resourceId: uuid('resource_id'),
  metadata: jsonb('metadata').default('{}'),
  createdAt: timestamp('created_at').defaultNow(),
})