import { pgTable, uuid, text, integer, numeric, boolean, jsonb, timestamp, date, uniqueIndex } from 'drizzle-orm/pg-core'

export const inventoryUnits = pgTable('inventory_units', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  symbol: text('symbol').notNull(),
  unitType: text('unit_type').notNull().default('custom'),
  organizationId: uuid('organization_id').notNull(),
  isSystem: boolean('is_system').default(false),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryWarehouses = pgTable('inventory_warehouses', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: text('code').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  country: text('country'),
  isActive: boolean('is_active').default(true),
  isDefault: boolean('is_default').default(false),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryLocations = pgTable('inventory_locations', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: text('code').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  warehouseId: uuid('warehouse_id').notNull(),
  rowLocation: text('row_location'),
  rack: text('rack'),
  bin: text('bin'),
  capacity: numeric('capacity', { precision: 12, scale: 2 }),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryItems = pgTable('inventory_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  productId: uuid('product_id').notNull(),
  warehouseId: uuid('warehouse_id').notNull(),
  locationId: uuid('location_id'),
  sku: text('sku'),
  quantityOnHand: numeric('quantity_on_hand', { precision: 12, scale: 3 }).notNull().default('0'),
  reservedQuantity: numeric('reserved_quantity', { precision: 12, scale: 3 }).notNull().default('0'),
  damagedQuantity: numeric('damaged_quantity', { precision: 12, scale: 3 }).notNull().default('0'),
  availableQuantity: numeric('available_quantity', { precision: 12, scale: 3 }).notNull().default('0'),
  unitCost: numeric('unit_cost', { precision: 14, scale: 4 }).notNull().default('0'),
  averageCost: numeric('average_cost', { precision: 14, scale: 4 }).notNull().default('0'),
  lastCountedAt: timestamp('last_counted_at'),
  lotNumber: text('lot_number'),
  expiryDate: date('expiry_date'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryStockMovements = pgTable('inventory_stock_movements', {
  id: uuid('id').primaryKey().defaultRandom(),
  movementType: text('movement_type').notNull(),
  productId: uuid('product_id').notNull(),
  warehouseId: uuid('warehouse_id').notNull(),
  locationId: uuid('location_id'),
  inventoryItemId: uuid('inventory_item_id'),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  unitCost: numeric('unit_cost', { precision: 14, scale: 4 }),
  fromWarehouseId: uuid('from_warehouse_id'),
  toWarehouseId: uuid('to_warehouse_id'),
  referenceType: text('reference_type'),
  referenceId: uuid('reference_id'),
  reason: text('reason'),
  notes: text('notes'),
  userId: uuid('user_id').notNull(),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const inventoryReservations = pgTable('inventory_reservations', {
  id: uuid('id').primaryKey().defaultRandom(),
  reservationType: text('reservation_type').notNull(),
  inventoryItemId: uuid('inventory_item_id').notNull(),
  productId: uuid('product_id').notNull(),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  reservedAt: timestamp('reserved_at').defaultNow(),
  consumedAt: timestamp('consumed_at'),
  cancelledAt: timestamp('cancelled_at'),
  status: text('status').notNull().default('active'),
  referenceId: uuid('reference_id'),
  referenceType: text('reference_type'),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const inventoryTransfers = pgTable('inventory_transfers', {
  id: uuid('id').primaryKey().defaultRandom(),
  transferNumber: text('transfer_number'),
  productId: uuid('product_id').notNull(),
  warehouseId: uuid('warehouse_id').notNull(),
  sourceLocationId: uuid('source_location_id'),
  destinationWarehouseId: uuid('destination_warehouse_id').notNull(),
  destinationLocationId: uuid('destination_location_id'),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  shippedQuantity: numeric('shipped_quantity', { precision: 12, scale: 3 }).default('0'),
  receivedQuantity: numeric('received_quantity', { precision: 12, scale: 3 }).default('0'),
  unitCost: numeric('unit_cost', { precision: 14, scale: 4 }),
  status: text('status').notNull().default('draft'),
  notes: text('notes'),
  requestedBy: uuid('requested_by').notNull(),
  approvedBy: uuid('approved_by'),
  receivedBy: uuid('received_by'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  shippedAt: timestamp('shipped_at'),
  receivedAt: timestamp('received_at'),
  cancelledAt: timestamp('cancelled_at'),
})

export const inventorySuppliers = pgTable('inventory_suppliers', {
  id: uuid('id').primaryKey().defaultRandom(),
  companyId: uuid('company_id').notNull(),
  supplierCode: text('supplier_code'),
  taxNumber: text('tax_number'),
  paymentTerms: text('payment_terms'),
  currency: text('currency').notNull().default('USD'),
  leadTimeDays: integer('lead_time_days').default(0),
  rating: numeric('rating', { precision: 3, scale: 2 }),
  ratingCount: integer('rating_count').default(0),
  isPreferred: boolean('is_preferred').default(false),
  isActive: boolean('is_active').default(true),
  contactName: text('contact_name'),
  contactEmail: text('contact_email'),
  contactPhone: text('contact_phone'),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventorySupplierProducts = pgTable('inventory_supplier_products', {
  id: uuid('id').primaryKey().defaultRandom(),
  supplierId: uuid('supplier_id').notNull(),
  productId: uuid('product_id').notNull(),
  supplierSku: text('supplier_sku'),
  supplierPrice: numeric('supplier_price', { precision: 14, scale: 4 }),
  currency: text('currency').notNull().default('USD'),
  minimumOrderQuantity: numeric('minimum_order_quantity', { precision: 12, scale: 3 }).default('1'),
  leadTimeDays: integer('lead_time_days').default(0),
  isPreferred: boolean('is_preferred').default(false),
  lastPurchasePrice: numeric('last_purchase_price', { precision: 14, scale: 4 }),
  lastPurchaseDate: date('last_purchase_date'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryPurchaseRequests = pgTable('inventory_purchase_requests', {
  id: uuid('id').primaryKey().defaultRandom(),
  requestNumber: text('request_number').notNull(),
  title: text('title').notNull(),
  description: text('description'),
  departmentId: uuid('department_id'),
  projectId: uuid('project_id'),
  requestedBy: uuid('requested_by').notNull(),
  approvedBy: uuid('approved_by'),
  status: text('status').notNull().default('draft'),
  totalAmount: numeric('total_amount', { precision: 14, scale: 2 }).default('0'),
  currency: text('currency').notNull().default('USD'),
  requestedAt: timestamp('requested_at'),
  approvedAt: timestamp('approved_at'),
  convertedAt: timestamp('converted_at'),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryPurchaseRequestLines = pgTable('inventory_purchase_request_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  requestId: uuid('request_id').notNull(),
  productId: uuid('product_id'),
  description: text('description').notNull(),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  unitId: uuid('unit_id'),
  unitPrice: numeric('unit_price', { precision: 14, scale: 4 }).default('0'),
  totalPrice: numeric('total_price', { precision: 14, scale: 2 }).default('0'),
  taxRateId: uuid('tax_rate_id'),
  taxAmount: numeric('tax_amount', { precision: 14, scale: 2 }).default('0'),
  preferredSupplierId: uuid('preferred_supplier_id'),
  sortOrder: integer('sort_order').default(0),
  createdAt: timestamp('created_at').defaultNow(),
})

export const inventoryPrApprovalSteps = pgTable('inventory_pr_approval_steps', {
  id: uuid('id').primaryKey().defaultRandom(),
  requestId: uuid('request_id').notNull(),
  stepOrder: integer('step_order').notNull(),
  roleRequired: text('role_required').notNull(),
  userId: uuid('user_id'),
  status: text('status').notNull().default('pending'),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),
  rejectedBy: uuid('rejected_by'),
  rejectedAt: timestamp('rejected_at'),
  notes: text('notes'),
})

export const inventoryPurchaseOrders = pgTable('inventory_purchase_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  financePurchaseOrderId: uuid('finance_purchase_order_id'),
  poNumber: text('po_number').notNull(),
  supplierId: uuid('supplier_id').notNull(),
  projectId: uuid('project_id'),
  departmentId: uuid('department_id'),
  status: text('status').notNull().default('draft'),
  currency: text('currency').notNull().default('USD'),
  subtotal: numeric('subtotal', { precision: 14, scale: 2 }).default('0'),
  taxAmount: numeric('tax_amount', { precision: 14, scale: 2 }).default('0'),
  shippingCost: numeric('shipping_cost', { precision: 14, scale: 2 }).default('0'),
  discountAmount: numeric('discount_amount', { precision: 14, scale: 2 }).default('0'),
  totalAmount: numeric('total_amount', { precision: 14, scale: 2 }).default('0'),
  expectedDelivery: date('expected_delivery'),
  issuedAt: timestamp('issued_at'),
  sentAt: timestamp('sent_at'),
  receivedAt: timestamp('received_at'),
  cancelledAt: timestamp('cancelled_at'),
  closedAt: timestamp('closed_at'),
  notes: text('notes'),
  terms: text('terms'),
  createdBy: uuid('created_by').notNull(),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryPurchaseOrderLines = pgTable('inventory_purchase_order_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  purchaseOrderId: uuid('purchase_order_id').notNull(),
  productId: uuid('product_id').notNull(),
  description: text('description'),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  receivedQuantity: numeric('received_quantity', { precision: 12, scale: 3 }).default('0'),
  unitId: uuid('unit_id'),
  unitPrice: numeric('unit_price', { precision: 14, scale: 4 }).default('0'),
  taxRateId: uuid('tax_rate_id'),
  taxAmount: numeric('tax_amount', { precision: 14, scale: 2 }).default('0'),
  lineTotal: numeric('line_total', { precision: 14, scale: 2 }).default('0'),
  sortOrder: integer('sort_order').default(0),
  createdAt: timestamp('created_at').defaultNow(),
})

export const inventoryGoodsReceipts = pgTable('inventory_goods_receipts', {
  id: uuid('id').primaryKey().defaultRandom(),
  poId: uuid('po_id').notNull(),
  receiptNumber: text('receipt_number').notNull(),
  warehouseId: uuid('warehouse_id').notNull(),
  locationId: uuid('location_id'),
  supplierId: uuid('supplier_id').notNull(),
  status: text('status').notNull().default('draft'),
  receivedDate: date('received_date').notNull(),
  currency: text('currency').notNull().default('USD'),
  totalAmount: numeric('total_amount', { precision: 14, scale: 2 }).default('0'),
  notes: text('notes'),
  receivedBy: uuid('received_by').notNull(),
  receivedAt: timestamp('received_at').defaultNow(),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const inventoryReceiptLines = pgTable('inventory_receipt_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  receiptId: uuid('receipt_id').notNull(),
  poLineId: uuid('po_line_id'),
  productId: uuid('product_id').notNull(),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 14, scale: 4 }).default('0'),
  receivedQuantity: numeric('received_quantity', { precision: 12, scale: 3 }).notNull(),
  damagedQuantity: numeric('damaged_quantity', { precision: 12, scale: 3 }).default('0'),
  missingQuantity: numeric('missing_quantity', { precision: 12, scale: 3 }).default('0'),
  rejectedQuantity: numeric('rejected_quantity', { precision: 12, scale: 3 }).default('0'),
  lineTotal: numeric('line_total', { precision: 14, scale: 2 }).default('0'),
  notes: text('notes'),
})

export const inventoryPurchaseReturns = pgTable('inventory_purchase_returns', {
  id: uuid('id').primaryKey().defaultRandom(),
  returnNumber: text('return_number').notNull(),
  poId: uuid('po_id'),
  supplierId: uuid('supplier_id').notNull(),
  warehouseId: uuid('warehouse_id').notNull(),
  reason: text('reason'),
  status: text('status').notNull().default('draft'),
  totalAmount: numeric('total_amount', { precision: 14, scale: 2 }).default('0'),
  currency: text('currency').notNull().default('USD'),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const inventoryReturnLines = pgTable('inventory_return_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  returnId: uuid('return_id').notNull(),
  productId: uuid('product_id').notNull(),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 14, scale: 4 }).default('0'),
  reason: text('reason'),
  lineTotal: numeric('line_total', { precision: 14, scale: 2 }).default('0'),
})

export const inventoryAdjustmentReasons = pgTable('inventory_adjustment_reasons', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: text('code').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  defaultDirection: text('default_direction').notNull().default('adjust'),
  requiresApproval: boolean('requires_approval').default(false),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const inventoryStockAdjustments = pgTable('inventory_stock_adjustments', {
  id: uuid('id').primaryKey().defaultRandom(),
  adjustmentNumber: text('adjustment_number').notNull(),
  productId: uuid('product_id').notNull(),
  warehouseId: uuid('warehouse_id').notNull(),
  locationId: uuid('location_id'),
  quantityBefore: numeric('quantity_before', { precision: 12, scale: 3 }).notNull(),
  quantityChange: numeric('quantity_change', { precision: 12, scale: 3 }).notNull(),
  quantityAfter: numeric('quantity_after', { precision: 12, scale: 3 }).notNull(),
  reasonId: uuid('reason_id'),
  reason: text('reason'),
  notes: text('notes'),
  status: text('status').notNull().default('pending'),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),
  createdBy: uuid('created_by').notNull(),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const inventoryReorderRules = pgTable('inventory_reorder_rules', {
  id: uuid('id').primaryKey().defaultRandom(),
  productId: uuid('product_id').notNull(),
  warehouseId: uuid('warehouse_id').notNull(),
  reorderPoint: numeric('reorder_point', { precision: 12, scale: 3 }).notNull(),
  reorderQuantity: numeric('reorder_quantity', { precision: 12, scale: 3 }).notNull(),
  maximumStock: numeric('maximum_stock', { precision: 12, scale: 3 }),
  isActive: boolean('is_active').default(true),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
})

export const inventoryProjectAllocations = pgTable('inventory_project_allocations', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').notNull(),
  productId: uuid('product_id').notNull(),
  requiredQuantity: numeric('required_quantity', { precision: 12, scale: 3 }).notNull(),
  allocatedQuantity: numeric('allocated_quantity', { precision: 12, scale: 3 }).default('0'),
  consumedQuantity: numeric('consumed_quantity', { precision: 12, scale: 3 }).default('0'),
  status: text('status').notNull().default('pending'),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const inventoryAssetAssignments = pgTable('inventory_asset_assignments', {
  id: uuid('id').primaryKey().defaultRandom(),
  productId: uuid('product_id').notNull(),
  employeeId: uuid('employee_id').notNull(),
  serialNumber: text('serial_number'),
  assignedDate: date('assigned_date').notNull(),
  returnDate: date('return_date'),
  status: text('status').notNull().default('assigned'),
  assignedBy: uuid('assigned_by').notNull(),
  notes: text('notes'),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

export const inventoryDocumentLinks = pgTable('inventory_document_links', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  entityType: text('entity_type').notNull(),
  entityId: uuid('entity_id').notNull(),
  organizationId: uuid('organization_id').notNull(),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const inventoryValuations = pgTable('inventory_valuations', {
  id: uuid('id').primaryKey().defaultRandom(),
  valuationDate: date('valuation_date').notNull(),
  method: text('method').notNull().default('average'),
  totalValue: numeric('total_value', { precision: 14, scale: 2 }).notNull(),
  totalCost: numeric('total_cost', { precision: 14, scale: 2 }),
  totalResaleValue: numeric('total_resale_value', { precision: 14, scale: 2 }),
  organizationId: uuid('organization_id').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const inventoryActivities = pgTable('inventory_activities', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  userId: uuid('user_id').notNull(),
  action: text('action').notNull(),
  resource: text('resource').notNull(),
  resourceId: uuid('resource_id'),
  metadata: jsonb('metadata').default('{}'),
  createdAt: timestamp('created_at').defaultNow(),
})
