import type { Permission } from '@/lib/auth/permissions'
import type { RiskLevel } from './document-tools'

export interface CalendarToolDefinition {
  name: string
  description: string
  permission: Permission
  risk: RiskLevel
  requiresApproval: boolean
  reversible: boolean
  audited: boolean
  module: string
  inputSchema?: Record<string, unknown>
  outputSchema?: Record<string, unknown>
  relatedEntities?: string[]
}

export const CALENDAR_TOOLS: CalendarToolDefinition[] = [
  {
    name: 'list_upcoming_events',
    description: 'List upcoming calendar events for the organization, including recurring occurrences',
    permission: 'calendar:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    outputSchema: { events: 'array' },
    relatedEntities: ['calendar_events', 'calendar_event_participants'],
  },
  {
    name: 'get_event_details',
    description: 'Get a single calendar event by ID with its participants',
    permission: 'calendar:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { eventId: 'uuid' },
    outputSchema: { event: 'object', participants: 'array' },
    relatedEntities: ['calendar_events', 'calendar_event_participants'],
  },
  {
    name: 'get_team_availability',
    description: 'Get team member availability slots for a given day',
    permission: 'calendar:availability:manage',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { userIds: 'array<uuid>' },
    outputSchema: { availability: 'array' },
    relatedEntities: ['calendar_availability'],
  },
  {
    name: 'find_schedule_slot',
    description: 'Find the next available meeting slot that works for all attendees within 30 days',
    permission: 'calendar:create',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { title: 'string', duration_minutes: 'number', attendee_ids: 'array<uuid>', start_date: 'string', start_time: 'string', buffer_minutes: 'number' },
    outputSchema: { found: 'boolean', start: 'datetime', end: 'datetime' },
    relatedEntities: ['calendar_events', 'calendar_availability'],
  },
  {
    name: 'create_event',
    description: 'Create a calendar event, optionally with a recurring rule (daily/weekly/monthly/yearly)',
    permission: 'calendar:create',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { input: 'object', recurrence: 'object' },
    outputSchema: { event: 'object' },
    relatedEntities: ['calendar_events'],
  },
  {
    name: 'update_event',
    description: 'Update an existing calendar event',
    permission: 'calendar:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { eventId: 'uuid', input: 'object' },
    outputSchema: { event: 'object' },
    relatedEntities: ['calendar_events'],
  },
  {
    name: 'cancel_event',
    description: 'Cancel a calendar event (marks it cancelled)',
    permission: 'calendar:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { eventId: 'uuid' },
    outputSchema: { event: 'object' },
    relatedEntities: ['calendar_events'],
  },
  {
    name: 'list_meetings',
    description: 'List meetings in the organization, optionally filtered by status or date range',
    permission: 'meeting:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    outputSchema: { meetings: 'array' },
    relatedEntities: ['meetings', 'meeting_participants'],
  },
  {
    name: 'get_meeting_summary',
    description: 'Get a meeting with its notes, decisions, and action items',
    permission: 'meeting:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid' },
    outputSchema: { meeting: 'object', notes: 'array', decisions: 'array', actionItems: 'array' },
    relatedEntities: ['meetings', 'meeting_notes', 'meeting_decisions', 'meeting_action_items'],
  },
  {
    name: 'list_meeting_action_items',
    description: 'List action items for a meeting',
    permission: 'meeting:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid' },
    outputSchema: { actionItems: 'array' },
    relatedEntities: ['meeting_action_items', 'tasks'],
  },
  {
    name: 'list_meeting_decisions',
    description: 'List decisions recorded in a meeting',
    permission: 'meeting:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid' },
    outputSchema: { decisions: 'array' },
    relatedEntities: ['meeting_decisions'],
  },
  {
    name: 'list_meeting_notes',
    description: 'List notes for a meeting',
    permission: 'meeting:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid' },
    outputSchema: { notes: 'array' },
    relatedEntities: ['meeting_notes', 'documents'],
  },
  {
    name: 'schedule_meeting',
    description: 'Schedule a new meeting with participants, linked to CRM/project entities when provided',
    permission: 'meeting:create',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { input: 'object', participants: 'array' },
    outputSchema: { meeting: 'object' },
    relatedEntities: ['meetings', 'meeting_participants', 'crm_companies', 'crm_deals', 'projects'],
  },
  {
    name: 'cancel_meeting',
    description: 'Cancel a scheduled meeting',
    permission: 'meeting:cancel',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid' },
    outputSchema: { meeting: 'object' },
    relatedEntities: ['meetings'],
  },
  {
    name: 'complete_meeting',
    description: 'Mark a meeting as completed',
    permission: 'meeting:update',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid' },
    outputSchema: { meeting: 'object' },
    relatedEntities: ['meetings'],
  },
  {
    name: 'list_communication_threads',
    description: 'List communication threads, optionally filtered by entity (company/contact/deal/project)',
    permission: 'communication:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    outputSchema: { threads: 'array' },
    relatedEntities: ['communication_threads', 'crm_companies', 'crm_contacts', 'crm_deals', 'projects'],
  },
  {
    name: 'get_thread_messages',
    description: 'Get messages in a communication thread',
    permission: 'communication:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { threadId: 'uuid' },
    outputSchema: { messages: 'array' },
    relatedEntities: ['communication_threads', 'communication_messages'],
  },
  {
    name: 'get_my_threads',
    description: 'Get communication threads the current user participates in',
    permission: 'communication:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    outputSchema: { threads: 'array' },
    relatedEntities: ['communication_threads', 'communication_thread_members'],
  },
  {
    name: 'list_email_connections',
    description: 'List the current user email provider connections (safe projection, no tokens)',
    permission: 'email:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    outputSchema: { connections: 'array' },
    relatedEntities: ['email_connections'],
  },
  {
    name: 'list_email_messages',
    description: 'List email messages in the organization',
    permission: 'email:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    outputSchema: { emails: 'array' },
    relatedEntities: ['email_messages', 'communication_threads'],
  },
  {
    name: 'send_email',
    description: 'Send an email to one or more recipients via the connected provider',
    permission: 'email:send',
    risk: 'medium',
    requiresApproval: true,
    reversible: false,
    audited: true,
    module: 'calendar',
    inputSchema: { input: 'object' },
    outputSchema: { email: 'object' },
    relatedEntities: ['email_messages'],
  },
  {
    name: 'find_availability',
    description: 'Check whether a proposed time range is free for a set of users, factoring in working hours, existing events, approved leave and organization holidays',
    permission: 'calendar:availability:manage',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { userIds: 'array<uuid>', start: 'datetime', end: 'datetime' },
    outputSchema: { perUser: 'object', hasConflict: 'boolean' },
    relatedEntities: ['calendar_availability', 'calendar_events', 'hr_leave_requests', 'hr_holidays'],
  },
  {
    name: 'get_meeting_history',
    description: 'Get meeting history for a company, deal, project, contact, or employee',
    permission: 'meeting:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { companyId: 'uuid', dealId: 'uuid', projectId: 'uuid', contactId: 'uuid', employeeId: 'uuid' },
    outputSchema: { meetings: 'array' },
    relatedEntities: ['meetings', 'crm_companies', 'crm_deals', 'projects', 'crm_contacts', 'hr_employees'],
  },
  {
    name: 'get_meeting_activities',
    description: 'Get the audit-style activity timeline for a meeting',
    permission: 'meeting:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid' },
    outputSchema: { activities: 'array' },
    relatedEntities: ['meeting_activities'],
  },
  {
    name: 'reschedule_meeting',
    description: 'Reschedule a meeting to a new start time, notifying participants and keeping its duration',
    permission: 'meeting:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { meetingId: 'uuid', startTime: 'datetime', endTime: 'datetime', reason: 'string' },
    outputSchema: { meeting: 'object' },
    relatedEntities: ['meetings', 'meeting_participants'],
  },
  {
    name: 'duplicate_event',
    description: 'Duplicate an existing calendar event',
    permission: 'calendar:create',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { eventId: 'uuid', newStartDate: 'datetime', newEndDate: 'datetime' },
    outputSchema: { event: 'object' },
    relatedEntities: ['calendar_events', 'calendar_event_participants'],
  },
  {
    name: 'reschedule_event',
    description: 'Reschedule a calendar event to a new start time, keeping its duration',
    permission: 'calendar:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { eventId: 'uuid', startDate: 'datetime', endDate: 'datetime' },
    outputSchema: { event: 'object' },
    relatedEntities: ['calendar_events'],
  },
  {
    name: 'edit_recurring_occurrence',
    description: 'Edit a single occurrence of a recurring event without affecting the rest of the series',
    permission: 'calendar:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { parentId: 'uuid', occurrenceDate: 'date', input: 'object' },
    outputSchema: { event: 'object' },
    relatedEntities: ['calendar_events'],
  },
  {
    name: 'update_recurring_series',
    description: 'Update all future occurrences of a recurring event series',
    permission: 'calendar:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { eventId: 'uuid', input: 'object' },
    outputSchema: { event: 'object' },
    relatedEntities: ['calendar_events'],
  },
  {
    name: 'cancel_recurring_series',
    description: 'Cancel a single occurrence of a recurring event or the entire series',
    permission: 'calendar:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'calendar',
    inputSchema: { parentId: 'uuid', occurrenceDate: 'date', allOccurrences: 'boolean' },
    outputSchema: { event: 'object', seriesCancelled: 'boolean' },
    relatedEntities: ['calendar_events'],
  },
  {
    name: 'convert_action_item_to_task',
    description: 'Turn a meeting action item into a tracked task, optionally linked to a project',
    permission: 'meeting:action:manage',
    risk: 'medium',
    requiresApproval: true,
    reversible: false,
    audited: true,
    module: 'calendar',
    inputSchema: { actionItemId: 'uuid', projectId: 'uuid', title: 'string' },
    outputSchema: { actionItem: 'object' },
    relatedEntities: ['meeting_action_items', 'tasks'],
  },
  {
    name: 'get_entity_communication',
    description: 'Get the communication timeline (threads + messages) for a customer, project, company, deal, or contact',
    permission: 'communication:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { entityType: 'string', entityId: 'uuid' },
    outputSchema: { threads: 'array' },
    relatedEntities: ['communication_threads', 'communication_messages', 'crm_companies', 'crm_contacts', 'crm_deals', 'projects'],
  },
  {
    name: 'get_communication_graph',
    description: 'Get the full communication graph for an entity: meetings, notes, decisions, action items, threads, and messages',
    permission: 'communication:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { entityType: 'string', entityId: 'uuid' },
    outputSchema: { graph: 'object' },
    relatedEntities: ['meetings', 'meeting_notes', 'meeting_decisions', 'meeting_action_items', 'communication_threads', 'communication_messages'],
  },
  {
    name: 'search_messages',
    description: 'Search communication messages by content',
    permission: 'communication:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { query: 'string' },
    outputSchema: { messages: 'array' },
    relatedEntities: ['communication_messages'],
  },
  {
    name: 'search_calendar',
    description: 'Global search across calendar events, meetings, threads, messages, notes, decisions, and action items',
    permission: 'calendar:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'calendar',
    inputSchema: { query: 'string' },
    outputSchema: { results: 'object' },
    relatedEntities: ['calendar_events', 'meetings', 'communication_threads', 'communication_messages', 'meeting_notes', 'meeting_decisions', 'meeting_action_items'],
  },
]

export function getCalendarTool(name: string): CalendarToolDefinition | undefined {
  return CALENDAR_TOOLS.find(t => t.name === name)
}

export function getCalendarToolsForRole(role?: string): CalendarToolDefinition[] {
  if (!role) return []
  if (role === 'super_admin' || role === 'admin') return CALENDAR_TOOLS
  return CALENDAR_TOOLS.filter(t => {
    const viewRoles = ['calendar:view', 'meeting:view', 'communication:view', 'email:view']
    return viewRoles.includes(t.permission) || (role === 'manager' && ['calendar:create', 'calendar:update', 'meeting:create', 'meeting:cancel', 'communication:send', 'email:send'].includes(t.permission))
  })
}