import type { Permission } from '@/lib/auth/permissions'

export type RiskLevel = 'low' | 'medium' | 'high'

export interface DocumentToolDefinition {
  name: string
  description: string
  permission: Permission
  risk: RiskLevel
  requiresApproval: boolean
  reversible: boolean
  audited: boolean
  module: string
}

export const DOCUMENT_TOOLS: DocumentToolDefinition[] = [
  {
    name: 'get_document_dashboard_stats',
    description: 'Get document dashboard metrics (total documents, published, pending approvals, contracts, knowledge, SOPs)',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_documents',
    description: 'List documents in the organization',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_document',
    description: 'Get a single document by ID',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'search_documents',
    description: 'Search documents by query',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_knowledge_articles',
    description: 'List knowledge base articles',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_sops',
    description: 'List standard operating procedures',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_policies',
    description: 'List company policies',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_contracts',
    description: 'List contracts and expiring contracts',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_pending_approvals',
    description: 'List pending document approvals assigned to or requested by the user',
    permission: 'documents:approve',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_expiring_contracts',
    description: 'List contracts expiring within a given number of days',
    permission: 'documents:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'get_document_activity',
    description: 'View recent document audit activity',
    permission: 'documents:activity:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'documents',
  },
  {
    name: 'create_document',
    description: 'Create a new document',
    permission: 'documents:create',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'update_document',
    description: 'Update an existing document',
    permission: 'documents:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'change_document_status',
    description: 'Change a document status',
    permission: 'documents:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'delete_document',
    description: 'Soft-delete a document',
    permission: 'documents:delete',
    risk: 'high',
    requiresApproval: true,
    reversible: false,
    audited: true,
    module: 'documents',
  },
  {
    name: 'create_folder',
    description: 'Create a document folder',
    permission: 'documents:create',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'share_document',
    description: 'Share a document with a user, team, department, or link',
    permission: 'documents:share',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'revoke_share',
    description: 'Revoke a document share',
    permission: 'documents:share',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'request_approval',
    description: 'Request approval for a document',
    permission: 'documents:approve',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'respond_to_approval',
    description: 'Approve or reject a pending document approval',
    permission: 'documents:approve',
    risk: 'high',
    requiresApproval: true,
    reversible: false,
    audited: true,
    module: 'documents',
  },
  {
    name: 'create_knowledge_article',
    description: 'Create a knowledge base article',
    permission: 'documents:knowledge:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'create_sop',
    description: 'Create a standard operating procedure',
    permission: 'documents:sops:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'create_policy',
    description: 'Create a company policy',
    permission: 'documents:policies:manage',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'create_contract',
    description: 'Create a contract record',
    permission: 'documents:contracts:manage',
    risk: 'high',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
  {
    name: 'update_contract',
    description: 'Update a contract record',
    permission: 'documents:contracts:manage',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'documents',
  },
]

export function getDocumentTool(name: string) {
  return DOCUMENT_TOOLS.find(t => t.name === name)
}

export function getDocumentToolsForRole(role?: string) {
  return DOCUMENT_TOOLS.filter(() => !role || role === 'admin' || role === 'super_admin')
}