import type { Permission } from '@/lib/auth/permissions'

export type RiskLevel = 'low' | 'medium' | 'high'

export interface HrToolDefinition {
  name: string
  description: string
  permission: Permission
  risk: RiskLevel
  requiresApproval: boolean
  reversible: boolean
  audited: boolean
  module: string
}

export const HR_TOOLS: HrToolDefinition[] = [
  {
    name: 'get_hr_dashboard_stats',
    description: 'Get HR dashboard metrics (headcount, attendance, leave, recruitment pipeline)',
    permission: 'hr:dashboard:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'get_headcount_by_department',
    description: 'Headcount breakdown by department',
    permission: 'hr:employees:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'get_attendance_trend',
    description: 'Attendance trend over recent days',
    permission: 'hr:attendance:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'get_leave_summary',
    description: 'Leave balances and usage summary by leave type',
    permission: 'hr:leave:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'get_recruitment_funnel',
    description: 'Candidate funnel counts by pipeline stage',
    permission: 'hr:recruitment:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'create_employee',
    description: 'Add a new employee record',
    permission: 'hr:employees:create',
    risk: 'high',
    requiresApproval: true,
    reversible: false,
    audited: true,
    module: 'hr',
  },
  {
    name: 'update_employee',
    description: 'Update an existing employee record',
    permission: 'hr:employees:update',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'archive_employee',
    description: 'Terminate / archive an employee',
    permission: 'hr:employees:update',
    risk: 'high',
    requiresApproval: true,
    reversible: false,
    audited: true,
    module: 'hr',
  },
  {
    name: 'create_department',
    description: 'Create a department',
    permission: 'hr:departments:manage',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'create_leave_request',
    description: 'Submit a leave request for an employee',
    permission: 'hr:leave:request',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'approve_leave_request',
    description: 'Approve or reject a pending leave request',
    permission: 'hr:leave:approve',
    risk: 'high',
    requiresApproval: true,
    reversible: false,
    audited: true,
    module: 'hr',
  },
  {
    name: 'record_attendance',
    description: 'Record attendance for an employee',
    permission: 'hr:attendance:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'create_job_opening',
    description: 'Create a job opening',
    permission: 'hr:recruitment:manage',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'create_candidate',
    description: 'Add a job candidate',
    permission: 'hr:recruitment:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'schedule_interview',
    description: 'Schedule an interview for a candidate',
    permission: 'hr:recruitment:manage',
    risk: 'medium',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'issue_offer',
    description: 'Create or send an employment offer',
    permission: 'hr:offers:manage',
    risk: 'high',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'create_goal',
    description: 'Create an HR goal',
    permission: 'hr:goals:manage',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'set_compensation',
    description: 'Set employee compensation',
    permission: 'hr:compensation:manage',
    risk: 'high',
    requiresApproval: true,
    reversible: true,
    audited: true,
    module: 'hr',
  },
  {
    name: 'get_workforce_capacity',
    description: 'Workforce capacity and utilization overview',
    permission: 'hr:capacity:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'get_org_chart',
    description: 'Organization chart with departments and reports',
    permission: 'hr:employees:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'get_hr_timeline',
    description: 'Recent HR activity timeline',
    permission: 'hr:activity:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
  {
    name: 'get_performance_distribution',
    description: 'Performance rating distribution across reviews',
    permission: 'hr:performance:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'hr',
  },
]

export function getHrTool(name: string) {
  return HR_TOOLS.find(t => t.name === name)
}

export function getHrToolsForRole(role?: string) {
  return HR_TOOLS.filter(t => !role || role === 'admin' || role === 'super_admin')
}