import type { Permission } from '@/lib/auth/permissions'
import type { RiskLevel } from './document-tools'
import { z } from 'zod'

export interface InventoryToolDefinition {
  name: string
  description: string
  permission: Permission
  risk: RiskLevel
  requiresApproval: boolean
  reversible: boolean
  audited: boolean
  module: string
  inputSchema?: z.ZodType
}

export const emptyArgs = z.object({}).strict()

export const productIdArgs = z.object({ productId: z.string().min(1) })

export const optionalProductArgs = z.object({ productId: z.string().min(1).optional(), warehouseId: z.string().min(1).optional() })

export const searchArgs = z.object({ query: z.string().optional(), warehouseId: z.string().min(1).optional(), lowStock: z.boolean().optional() })

export const movementsArgs = z.object({ productId: z.string().min(1).optional(), warehouseId: z.string().min(1).optional(), type: z.string().min(1).optional(), limit: z.number().int().positive().max(200).optional() })

export const singleIdArgs = z.object({
  id: z.string().min(1).optional(),
  requestId: z.string().min(1).optional(),
  poId: z.string().min(1).optional(),
  supplierId: z.string().min(1).optional(),
  projectId: z.string().min(1).optional(),
})

export const writeArgs = z.object({ input: z.record(z.string(), z.unknown()) })

export const writeWithLinesArgs = z.object({
  input: z.record(z.string(), z.unknown()),
  lines: z.array(z.record(z.string(), z.unknown())).optional(),
})

export const INVENTORY_TOOLS: InventoryToolDefinition[] = [
  {
    name: 'get_inventory_dashboard',
    description: 'Get inventory dashboard metrics: total stock value, low-stock items, out-of-stock count, tracked products, recent activity',
    permission: 'inventory:dashboard:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: emptyArgs,
  },
  {
    name: 'get_low_stock_items',
    description: 'Find products whose available stock is at or below their reorder point',
    permission: 'inventory:stock:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: emptyArgs,
  },
  {
    name: 'get_backordered_orders',
    description: 'List purchase orders that have not been fully received',
    permission: 'inventory:procurement:purchase_order:create',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: emptyArgs,
  },
  {
    name: 'get_recent_suppliers',
    description: 'Get recently created or updated suppliers with their preferred status and lead times',
    permission: 'inventory:suppliers:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: emptyArgs,
  },
  {
    name: 'search_inventory',
    description: 'Search products by name, SKU, or warehouse. Supports filtering by supplier, category, and stock thresholds.',
    permission: 'inventory:products:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: searchArgs,
  },
  {
    name: 'get_reorder_suggestions',
    description: 'Calculate reorder suggestions based on current stock vs reorder rules, including EOQ-style recommendations',
    permission: 'inventory:procurement:reorder:manage',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: emptyArgs,
  },
  {
    name: 'get_inventory_valuation',
    description: 'Get inventory valuation report using average cost and FIFO methods',
    permission: 'inventory:valuation:manage',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: emptyArgs,
  },
  {
    name: 'get_purchase_request',
    description: 'Get a purchase request by ID with its line items and approval steps',
    permission: 'inventory:procurement:purchase_request:create',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'create_purchase_request',
    description: 'Create a purchase request with line items from a PR/supplier, optionally converting from a reorder suggestion',
    permission: 'inventory:procurement:purchase_request:create',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeWithLinesArgs,
  },
  {
    name: 'create_stock_movement',
    description: 'Record a stock movement (receipt, issue, adjustment, return, production, opening balance, transfer)',
    permission: 'inventory:stock:adjust',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'create_transfer',
    description: 'Create a stock transfer between warehouses or locations',
    permission: 'inventory:stock:transfer',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'create_purchase_order',
    description: 'Create a purchase order from a supplier with line items, optionally converting from a purchase request',
    permission: 'inventory:procurement:purchase_order:create',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeWithLinesArgs,
  },
  {
    name: 'receive_goods',
    description: 'Record goods receipt against a purchase order, increasing stock levels',
    permission: 'inventory:procurement:receiving',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeWithLinesArgs,
  },
  {
    name: 'create_purchase_return',
    description: 'Create a return to supplier for damaged or excess goods, decreasing stock levels',
    permission: 'inventory:procurement:return',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeWithLinesArgs,
  },
  {
    name: 'create_asset_assignment',
    description: 'Assign a product (asset) to an employee, tracking serial number and assignment date',
    permission: 'inventory:assets:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'get_supplier_performance',
    description: 'Get supplier performance metrics: order count, on-time delivery rate, lead time, average price',
    permission: 'inventory:suppliers:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: z.object({ supplierId: z.string().min(1) }),
  },
  {
    name: 'get_stock_level',
    description: 'Get current stock level (on-hand, reserved, available) for a product, optionally per warehouse',
    permission: 'inventory:stock:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: optionalProductArgs,
  },
  {
    name: 'get_available_stock',
    description: 'Get available (sellable) stock for a product across all warehouses',
    permission: 'inventory:stock:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: z.object({ productId: z.string().min(1).optional() }),
  },
  {
    name: 'get_stock_movements',
    description: 'List recent stock movements, optionally filtered by product, warehouse, or type',
    permission: 'inventory:stock:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: movementsArgs,
  },
  {
    name: 'get_reservations',
    description: 'List active stock reservations, optionally filtered by product',
    permission: 'inventory:stock:reserve',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: z.object({ productId: z.string().min(1).optional() }),
  },
  {
    name: 'reserve_stock',
    description: 'Reserve a quantity of a product for an order, customer, department, or project',
    permission: 'inventory:stock:reserve',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'release_stock',
    description: 'Release a previously reserved quantity of a product',
    permission: 'inventory:stock:reserve',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'adjust_stock',
    description: 'Record a stock adjustment (positive or negative quantity change) for a product in a warehouse',
    permission: 'inventory:stock:adjust',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'transfer_stock',
    description: 'Create a stock transfer between warehouses or locations',
    permission: 'inventory:stock:transfer',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'submit_purchase_request',
    description: 'Submit a purchase request for review/approval',
    permission: 'inventory:procurement:purchase_request:approve',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'approve_purchase_request',
    description: 'Approve a purchase request',
    permission: 'inventory:procurement:purchase_request:approve',
    risk: 'medium',
    requiresApproval: false,
    reversible: false,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'approve_purchase_order',
    description: 'Approve a purchase order before sending to the supplier',
    permission: 'inventory:procurement:purchase_order:approve',
    risk: 'medium',
    requiresApproval: false,
    reversible: false,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'send_purchase_order',
    description: 'Mark a purchase order as sent to the supplier',
    permission: 'inventory:procurement:purchase_order:send',
    risk: 'medium',
    requiresApproval: false,
    reversible: false,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'get_supplier',
    description: 'Get supplier details by ID',
    permission: 'inventory:suppliers:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'find_suppliers_for_product',
    description: 'Find suppliers that supply a given product with their pricing and lead times',
    permission: 'inventory:suppliers:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: productIdArgs,
  },
  {
    name: 'get_supplier_pricing',
    description: 'Get supplier pricing for a product across all suppliers (best price first)',
    permission: 'inventory:suppliers:read',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: productIdArgs,
  },
  {
    name: 'get_project_material_requirements',
    description: 'Get material requirements and current inventory status for a project',
    permission: 'inventory:projects:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: z.object({ projectId: z.string().min(1) }),
  },
  {
    name: 'get_project_material_availability',
    description: 'Get material availability vs required quantities for a project, including shortfalls',
    permission: 'inventory:projects:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: z.object({ projectId: z.string().min(1) }),
  },
  {
    name: 'create_reorder_rule',
    description: 'Create or update a reorder rule for a product in a warehouse',
    permission: 'inventory:procurement:reorder:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'generate_inventory_report',
    description: 'Generate an inventory summary report: valuation, stock levels, low stock, movements',
    permission: 'inventory:reports:view',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: emptyArgs,
  },
  {
    name: 'create_product',
    description: 'Create a new product catalog entry (name, SKU, price, unit, type)',
    permission: 'inventory:products:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'update_product',
    description: 'Update an existing product catalog entry (name, SKU, price, unit, type, status)',
    permission: 'inventory:products:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
  {
    name: 'cancel_purchase_request',
    description: 'Cancel a purchase request that has not yet been converted to an order',
    permission: 'inventory:procurement:purchase_request:create',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'update_purchase_request',
    description: 'Update a draft or pending-review purchase request header and line items',
    permission: 'inventory:procurement:purchase_request:create',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeWithLinesArgs,
  },
  {
    name: 'cancel_purchase_order',
    description: 'Cancel a purchase order that has not been fully received',
    permission: 'inventory:procurement:purchase_order:create',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'update_purchase_order',
    description: 'Update a draft purchase order header and line items',
    permission: 'inventory:procurement:purchase_order:create',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeWithLinesArgs,
  },
  {
    name: 'approve_purchase_return',
    description: 'Approve a purchase return',
    permission: 'inventory:procurement:return',
    risk: 'medium',
    requiresApproval: false,
    reversible: false,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'cancel_purchase_return',
    description: 'Cancel a draft purchase return',
    permission: 'inventory:procurement:return',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'get_purchase_return_lines',
    description: 'Get the line items of a purchase return',
    permission: 'inventory:procurement:return',
    risk: 'low',
    requiresApproval: false,
    reversible: true,
    audited: false,
    module: 'inventory',
    inputSchema: singleIdArgs,
  },
  {
    name: 'update_supplier',
    description: 'Update supplier contact, rating, lead time, preferred status, and notes',
    permission: 'inventory:suppliers:manage',
    risk: 'medium',
    requiresApproval: false,
    reversible: true,
    audited: true,
    module: 'inventory',
    inputSchema: writeArgs,
  },
]

export function getInventoryTool(name: string): InventoryToolDefinition | undefined {
  return INVENTORY_TOOLS.find(t => t.name === name)
}

export function getInventoryToolsForRole(role?: string): InventoryToolDefinition[] {
  if (!role) return []
  if (role === 'super_admin' || role === 'admin') return INVENTORY_TOOLS
  return INVENTORY_TOOLS.filter(t => {
    const viewRoles = ['inventory:dashboard:view', 'inventory:stock:read', 'inventory:products:read', 'inventory:suppliers:read']
    return viewRoles.includes(t.permission) || (role === 'manager' && ['inventory:procurement:purchase_request:create', 'inventory:procurement:purchase_order:create', 'inventory:procurement:reorder:manage', 'inventory:reports:view'].includes(t.permission))
  })
}
