export const PERMISSIONS = {
  // CRM
  crm_dashboard_view: { name: 'View CRM Dashboard', resource: 'crm', action: 'view_dashboard' },
  crm_lead_view: { name: 'View Leads', resource: 'crm_lead', action: 'view' },
  crm_lead_create: { name: 'Create Leads', resource: 'crm_lead', action: 'create' },
  crm_lead_update: { name: 'Update Leads', resource: 'crm_lead', action: 'update' },
  crm_lead_delete: { name: 'Delete Leads', resource: 'crm_lead', action: 'delete' },
  crm_contact_view: { name: 'View Contacts', resource: 'crm_contact', action: 'view' },
  crm_contact_create: { name: 'Create Contacts', resource: 'crm_contact', action: 'create' },
  crm_contact_update: { name: 'Update Contacts', resource: 'crm_contact', action: 'update' },
  crm_contact_delete: { name: 'Delete Contacts', resource: 'crm_contact', action: 'delete' },
  crm_company_view: { name: 'View Companies', resource: 'crm_company', action: 'view' },
  crm_company_create: { name: 'Create Companies', resource: 'crm_company', action: 'create' },
  crm_company_update: { name: 'Update Companies', resource: 'crm_company', action: 'update' },
  crm_company_delete: { name: 'Delete Companies', resource: 'crm_company', action: 'delete' },
  crm_deal_view: { name: 'View Deals', resource: 'crm_deal', action: 'view' },
  crm_deal_create: { name: 'Create Deals', resource: 'crm_deal', action: 'create' },
  crm_deal_update: { name: 'Update Deals', resource: 'crm_deal', action: 'update' },
  crm_deal_delete: { name: 'Delete Deals', resource: 'crm_deal', action: 'delete' },
  crm_pipeline_manage: { name: 'Manage Pipelines', resource: 'crm_pipeline', action: 'manage' },
  crm_activity_log: { name: 'Log Activities', resource: 'crm_activity', action: 'log' },
  crm_note_manage: { name: 'Manage Notes', resource: 'crm_note', action: 'manage' },
  crm_task_manage: { name: 'Manage Tasks', resource: 'crm_task', action: 'manage' },

  // Organization
  organization_view: { name: 'View Organization', resource: 'organization', action: 'view' },
  organization_create: { name: 'Create Organization', resource: 'organization', action: 'create' },
  organization_update: { name: 'Update Organization', resource: 'organization', action: 'update' },
  organization_delete: { name: 'Delete Organization', resource: 'organization', action: 'delete' },
  organization_manage_members: { name: 'Manage Members', resource: 'organization', action: 'manage_members' },

  // Workspace
  workspace_view: { name: 'View Workspace', resource: 'workspace', action: 'view' },
  workspace_create: { name: 'Create Workspace', resource: 'workspace', action: 'create' },
  workspace_update: { name: 'Update Workspace', resource: 'workspace', action: 'update' },
  workspace_delete: { name: 'Delete Workspace', resource: 'workspace', action: 'delete' },

  // Team
  team_view: { name: 'View Team', resource: 'team', action: 'view' },
  team_create: { name: 'Create Team', resource: 'team', action: 'create' },
  team_update: { name: 'Update Team', resource: 'team', action: 'update' },
  team_delete: { name: 'Delete Team', resource: 'team', action: 'delete' },

  // Project
  project_view: { name: 'View Project', resource: 'project', action: 'view' },
  project_create: { name: 'Create Project', resource: 'project', action: 'create' },
  project_update: { name: 'Update Project', resource: 'project', action: 'update' },
  project_delete: { name: 'Delete Project', resource: 'project', action: 'delete' },

  // Task
  task_view: { name: 'View Task', resource: 'task', action: 'view' },
  task_create: { name: 'Create Task', resource: 'task', action: 'create' },
  task_update: { name: 'Update Task', resource: 'task', action: 'update' },
  task_delete: { name: 'Delete Task', resource: 'task', action: 'delete' },
  task_assign: { name: 'Assign Task', resource: 'task', action: 'assign' },

  // Billing
  billing_view: { name: 'View Billing', resource: 'billing', action: 'view' },
  billing_manage: { name: 'Manage Billing', resource: 'billing', action: 'manage' },

  // Members
  member_view: { name: 'View Members', resource: 'member', action: 'view' },
  member_invite: { name: 'Invite Members', resource: 'member', action: 'invite' },
  member_remove: { name: 'Remove Members', resource: 'member', action: 'remove' },
  member_update_role: { name: 'Update Member Role', resource: 'member', action: 'update_role' },

  // Settings
  settings_view: { name: 'View Settings', resource: 'settings', action: 'view' },
  settings_update: { name: 'Update Settings', resource: 'settings', action: 'update' },

  // API Keys
  api_key_view: { name: 'View API Keys', resource: 'api_key', action: 'view' },
  api_key_create: { name: 'Create API Key', resource: 'api_key', action: 'create' },
  api_key_delete: { name: 'Delete API Key', resource: 'api_key', action: 'delete' },

  // Activity & Audit
  activity_view: { name: 'View Activity', resource: 'activity', action: 'view' },
  audit_view: { name: 'View Audit Logs', resource: 'audit', action: 'view' },

  // HR
  hr_dashboard_view: { name: 'View HR Dashboard', resource: 'hr', action: 'view_dashboard' },
  hr_employee_view: { name: 'View Employees', resource: 'hr_employee', action: 'view' },
  hr_employee_create: { name: 'Create Employees', resource: 'hr_employee', action: 'create' },
  hr_employee_update: { name: 'Update Employees', resource: 'hr_employee', action: 'update' },
  hr_employee_archive: { name: 'Archive Employees', resource: 'hr_employee', action: 'archive' },
  hr_department_view: { name: 'View Departments', resource: 'hr_department', action: 'view' },
  hr_department_manage: { name: 'Manage Departments', resource: 'hr_department', action: 'manage' },
  hr_team_view: { name: 'View Teams', resource: 'hr_team', action: 'view' },
  hr_team_manage: { name: 'Manage Teams', resource: 'hr_team', action: 'manage' },
  hr_attendance_view: { name: 'View Attendance', resource: 'hr_attendance', action: 'view' },
  hr_attendance_manage: { name: 'Manage Attendance', resource: 'hr_attendance', action: 'manage' },
  hr_leave_view: { name: 'View Leave', resource: 'hr_leave', action: 'view' },
  hr_leave_request: { name: 'Request Leave', resource: 'hr_leave', action: 'request' },
  hr_leave_approve: { name: 'Approve Leave', resource: 'hr_leave', action: 'approve' },
  hr_recruitment_view: { name: 'View Recruitment', resource: 'hr_recruitment', action: 'view' },
  hr_recruitment_manage: { name: 'Manage Recruitment', resource: 'hr_recruitment', action: 'manage' },
  hr_offer_manage: { name: 'Issue Offers', resource: 'hr_offer', action: 'manage' },
  hr_onboarding_manage: { name: 'Manage Onboarding', resource: 'hr_onboarding', action: 'manage' },
  hr_offboarding_manage: { name: 'Manage Offboarding', resource: 'hr_offboarding', action: 'manage' },
  hr_skill_view: { name: 'View Skills', resource: 'hr_skill', action: 'view' },
  hr_skill_manage: { name: 'Manage Skills', resource: 'hr_skill', action: 'manage' },
  hr_capacity_view: { name: 'View Capacity', resource: 'hr_capacity', action: 'view' },
  hr_capacity_manage: { name: 'Manage Capacity', resource: 'hr_capacity', action: 'manage' },
  hr_performance_view: { name: 'View Performance', resource: 'hr_performance', action: 'view' },
  hr_performance_manage: { name: 'Manage Performance', resource: 'hr_performance', action: 'manage' },
  hr_goal_view: { name: 'View Goals', resource: 'hr_goal', action: 'view' },
  hr_goal_manage: { name: 'Manage Goals', resource: 'hr_goal', action: 'manage' },
  hr_compensation_view: { name: 'View Compensation', resource: 'hr_compensation', action: 'view' },
  hr_compensation_manage: { name: 'Manage Compensation', resource: 'hr_compensation', action: 'manage' },
  hr_report_view: { name: 'View HR Reports', resource: 'hr_report', action: 'view' },
  hr_activity_view: { name: 'View HR Activity', resource: 'hr_activity', action: 'view' },

  // Documents & Knowledge
  document_view: { name: 'View Documents', resource: 'document', action: 'view' },
  document_create: { name: 'Create Documents', resource: 'document', action: 'create' },
  document_update: { name: 'Update Documents', resource: 'document', action: 'update' },
  document_delete: { name: 'Delete Documents', resource: 'document', action: 'delete' },
  document_share: { name: 'Share Documents', resource: 'document', action: 'share' },
  document_approve: { name: 'Approve Documents', resource: 'document', action: 'approve' },
  document_publish: { name: 'Publish Documents', resource: 'document', action: 'publish' },
  document_template_manage: { name: 'Manage Templates', resource: 'document_template', action: 'manage' },
  knowledge_manage: { name: 'Manage Knowledge', resource: 'knowledge', action: 'manage' },
  document_sop_manage: { name: 'Manage SOPs', resource: 'document_sop', action: 'manage' },
  document_policy_manage: { name: 'Manage Policies', resource: 'document_policy', action: 'manage' },
  document_contract_manage: { name: 'Manage Contracts', resource: 'document_contract', action: 'manage' },
  document_expiration_manage: { name: 'Manage Expiration', resource: 'document_expiration', action: 'manage' },
  document_activity_view: { name: 'View Document Activity', resource: 'document_activity', action: 'view' },

  // Inventory & Procurement
  inventory_dashboard_view: { name: 'View Inventory Dashboard', resource: 'inventory_dashboard', action: 'view' },
  inventory_products_read: { name: 'View Products', resource: 'product', action: 'read' },
  inventory_products_manage: { name: 'Manage Products', resource: 'product', action: 'manage' },
  inventory_categories_manage: { name: 'Manage Categories', resource: 'category', action: 'manage' },
  inventory_units_manage: { name: 'Manage Units', resource: 'unit', action: 'manage' },
  inventory_warehouses_manage: { name: 'Manage Warehouses', resource: 'warehouse', action: 'manage' },
  inventory_warehouses_read: { name: 'View Warehouses', resource: 'warehouse', action: 'read' },
  inventory_stock_read: { name: 'View Stock', resource: 'stock', action: 'read' },
  inventory_stock_adjust: { name: 'Adjust Stock', resource: 'stock', action: 'adjust' },
  inventory_stock_transfer: { name: 'Transfer Stock', resource: 'stock', action: 'transfer' },
  inventory_stock_reserve: { name: 'Reserve Stock', resource: 'stock', action: 'reserve' },
  inventory_stock_receive: { name: 'Receive Stock', resource: 'stock', action: 'receive' },
  inventory_suppliers_manage: { name: 'Manage Suppliers', resource: 'supplier', action: 'manage' },
  inventory_suppliers_read: { name: 'View Suppliers', resource: 'supplier', action: 'read' },
  inventory_procurement_purchase_request_create: { name: 'Create Purchase Request', resource: 'purchase_request', action: 'create' },
  inventory_procurement_purchase_request_approve: { name: 'Approve Purchase Request', resource: 'purchase_request', action: 'approve' },
  inventory_procurement_purchase_order_create: { name: 'Create Purchase Order', resource: 'purchase_order', action: 'create' },
  inventory_procurement_purchase_order_approve: { name: 'Approve Purchase Order', resource: 'purchase_order', action: 'approve' },
  inventory_procurement_purchase_order_send: { name: 'Send Purchase Order', resource: 'purchase_order', action: 'send' },
  inventory_procurement_receiving: { name: 'Goods Receiving', resource: 'goods_receipt', action: 'manage' },
  inventory_procurement_return: { name: 'Purchase Returns', resource: 'purchase_return', action: 'manage' },
  inventory_procurement_reorder_manage: { name: 'Manage Reorder Rules', resource: 'reorder_rule', action: 'manage' },
  inventory_reports_view: { name: 'View Inventory Reports', resource: 'report', action: 'view' },
  inventory_valuation_manage: { name: 'Manage Inventory Valuation', resource: 'valuation', action: 'manage' },
  inventory_assets_view: { name: 'View Asset Assignments', resource: 'asset_assignment', action: 'view' },
  inventory_assets_manage: { name: 'Manage Asset Assignments', resource: 'asset_assignment', action: 'manage' },
  inventory_projects_view: { name: 'View Project Allocations', resource: 'project_allocation', action: 'view' },
  inventory_projects_manage: { name: 'Manage Project Allocations', resource: 'project_allocation', action: 'manage' },
  inventory_activity_view: { name: 'View Inventory Activity', resource: 'inventory_activity', action: 'view' },

  // Calendar, Communication & Meetings
  calendar_view: { name: 'View Calendar', resource: 'calendar', action: 'view' },
  calendar_create: { name: 'Create Events', resource: 'calendar', action: 'create' },
  calendar_update: { name: 'Update Events', resource: 'calendar', action: 'update' },
  calendar_delete: { name: 'Delete Events', resource: 'calendar', action: 'delete' },
  calendar_availability_manage: { name: 'Manage Availability', resource: 'calendar_availability', action: 'manage' },
  calendar_integration_manage: { name: 'Manage Calendar Integrations', resource: 'calendar_integration', action: 'manage' },
  calendar_activity_view: { name: 'View Calendar Activity', resource: 'calendar_activity', action: 'view' },
  meeting_view: { name: 'View Meetings', resource: 'meeting', action: 'view' },
  meeting_create: { name: 'Create Meetings', resource: 'meeting', action: 'create' },
  meeting_update: { name: 'Update Meetings', resource: 'meeting', action: 'update' },
  meeting_cancel: { name: 'Cancel Meetings', resource: 'meeting', action: 'cancel' },
  meeting_manage: { name: 'Manage Meetings', resource: 'meeting', action: 'manage' },
  meeting_notes_manage: { name: 'Manage Meeting Notes', resource: 'meeting_notes', action: 'manage' },
  meeting_decision_manage: { name: 'Manage Decisions', resource: 'meeting_decision', action: 'manage' },
  meeting_action_manage: { name: 'Manage Action Items', resource: 'meeting_action', action: 'manage' },
  communication_view: { name: 'View Communication', resource: 'communication', action: 'view' },
  communication_send: { name: 'Send Messages', resource: 'communication', action: 'send' },
  communication_manage: { name: 'Manage Communication', resource: 'communication', action: 'manage' },
  email_send: { name: 'Send Email', resource: 'email', action: 'send' },
  email_view: { name: 'View Email', resource: 'email', action: 'view' },
  email_connection_manage: { name: 'Manage Email Connections', resource: 'email_connection', action: 'manage' },
} as const

export type PermissionSlug = keyof typeof PERMISSIONS

export const ROLES = {
  super_admin: {
    name: 'Super Admin',
    level: 100,
    permissions: Object.keys(PERMISSIONS),
  },
  admin: {
    name: 'Admin',
    level: 80,
    permissions: Object.keys(PERMISSIONS),
  },
  manager: {
    name: 'Manager',
    level: 60,
    permissions: [
      'crm_dashboard_view',
      'crm_lead_view', 'crm_lead_create', 'crm_lead_update',
      'crm_contact_view', 'crm_contact_create', 'crm_contact_update',
      'crm_company_view', 'crm_company_create', 'crm_company_update',
      'crm_deal_view', 'crm_deal_create', 'crm_deal_update',
      'crm_pipeline_manage',
      'crm_activity_log',
      'crm_note_manage',
      'crm_task_manage',
      'organization_view',
      'workspace_view', 'workspace_create', 'workspace_update',
      'team_view', 'team_create', 'team_update',
      'project_view', 'project_create', 'project_update',
      'task_view', 'task_create', 'task_update', 'task_assign',
      'member_view', 'member_invite',
      'settings_view', 'settings_update',
      'activity_view',
      'hr_dashboard_view',
      'hr_employee_view', 'hr_employee_create', 'hr_employee_update',
      'hr_department_view', 'hr_department_manage',
      'hr_team_view', 'hr_team_manage',
      'hr_attendance_view', 'hr_attendance_manage',
      'hr_leave_view', 'hr_leave_approve',
      'hr_recruitment_view',
      'hr_skill_view',
      'hr_capacity_view',
      'hr_performance_view',
      'hr_goal_view', 'hr_goal_manage',
      'hr_report_view',
      'hr_activity_view',
      'document_view', 'document_create', 'document_update',
      'document_share', 'document_approve', 'document_publish',
      'document_template_manage', 'knowledge_manage',
      'document_sop_manage', 'document_policy_manage', 'document_contract_manage',
      'inventory_dashboard_view', 'inventory_products_read',
      'inventory_warehouses_read', 'inventory_stock_read',
      'inventory_assets_view', 'inventory_projects_view',
      'calendar_view', 'calendar_create', 'calendar_update',
      'calendar_availability_manage', 'calendar_activity_view',
      'meeting_view', 'meeting_create', 'meeting_update', 'meeting_cancel',
      'meeting_notes_manage', 'meeting_decision_manage', 'meeting_action_manage',
      'communication_view', 'communication_send', 'communication_manage',
      'email_send', 'email_view',
    ],
  },
  employee: {
    name: 'Employee',
    level: 40,
    permissions: [
      'crm_dashboard_view',
      'crm_lead_view', 'crm_lead_update',
      'crm_contact_view', 'crm_contact_update',
      'crm_company_view',
      'crm_deal_view',
      'crm_activity_log',
      'crm_note_manage',
      'crm_task_manage',
      'organization_view',
      'workspace_view',
      'team_view',
      'project_view',
      'task_view', 'task_update',
      'member_view',
      'settings_view',
      'activity_view',
      'hr_dashboard_view',
      'hr_employee_view',
      'hr_department_view',
      'hr_team_view',
      'hr_attendance_view', 'hr_attendance_manage',
      'hr_leave_view', 'hr_leave_request',
      'hr_skill_view', 'hr_skill_manage',
      'hr_performance_view',
      'hr_goal_view',
      'hr_activity_view',
      'document_view', 'document_create', 'document_update',
      'calendar_view', 'calendar_create',
      'meeting_view', 'meeting_create', 'meeting_update',
      'meeting_notes_manage', 'meeting_action_manage',
      'communication_view', 'communication_send',
      'email_view',
    ],
  },
  guest: {
    name: 'Guest',
    level: 20,
    permissions: [
      'organization_view',
      'project_view',
      'task_view',
      'calendar_view',
      'meeting_view',
      'communication_view',
    ],
  },
} as const

export type RoleSlug = keyof typeof ROLES
